const PLATFORM_HUBSPOT = require('./HUBSPOT')
const PLATFORM_GLOBAL_PAYMENTS = require('./GLOBAL_PAYMENTS')
const PLATFORM_QUICKBOOKS = require('./QUICKBOOKS')
const PLATFORM_XERO = require('./XERO')
const PLATFORM_AUTOCAB = require('./AUTOCAB')
const PLATFORM_PEEREDGE = require('./PEEREDGE')
const PLATFORM_FREEAGENT = require('./FREEAGENT')
const PLATFORM_COMMUSOFT = require('./COMMUSOFT')

module.exports = [
  PLATFORM_HUBSPOT,
  PLATFORM_GLOBAL_PAYMENTS,
  PLATFORM_QUICKBOOKS,
  PLATFORM_XERO,
  PLATFORM_AUTOCAB,
  PLATFORM_PEEREDGE,
  PLATFORM_FREEAGENT,
  PLATFORM_COMMUSOFT
]
