const PLATFORM_HUBSPOT = require('./HUBSPOT')
const PLATFORM_QUICKBOOKS = require('./QUICKBOOKS')
const PLATFORM_XERO = require('./XERO')
const PLATFORM_PEEREDGE = require('./PEEREDGE')

module.exports = [
  PLATFORM_HUBSPOT,
  PLATFORM_QUICKBOOKS,
  PLATFORM_XERO,
  PLATFORM_PEEREDGE
]
